# 头部菜单，title: link
menu:
  me: /about
  github: https://github.com/xutingyin
  cnblogs: https://cnblogs.com/mworld
  jianshu: https://www.jianshu.com/u/692ab30e4b5b
  500px: https://500px.me/mworld
  # unsplash: https://unsplash.com/@codingsunshine
  归档: /archives
# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: /music/tea-of-mouant.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: 'a396afe529734b15300f'
    # 应用秘钥
    clientSecret: '0ae7c1790f9a5cbc2b7339c12a82d58fe58f9567'
    # issue仓库名
    repo: 'xutingyin.github.io'
    # Github名
    owner: 'xutingyin'
    # Github名
    admin: ['xutingyin']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: xutingyin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-69833742-2

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml

## 是否展示备案号
### beian: false	# 不开启
beian: 鄂ICP备15003996号
